# Entrada e Saída de Dados

___

### Gerando DataFrames dados para os exemplos

No Pandas, temos uma variedade de métodos que nos permitem importar dados de várias fontes e
exportar nossos dados para outros locais. Esses métodos são essenciais para manipular dados de
forma eficaz em nossos projetos de análise de dados. Iremos aprender os seguintes mátodos:

* read_csv()    - Lê dados de arquivo .csv
* to_csv()      - Grava dados em arquvo .csv
* read_excel()  - Lê dados de arquivo .xlsx
* read_html()   - Lê dados de arquivo .html

Método read_csv()

In [ ]:
# Metodo para ler um arquivo CSV com pandas
import pandas as pd
df = pd.read_csv("dados_cartao.csv", sep=',', decimal=".")
df

,NumeroCartao,data_compra,hora_compra,estabelecimento,categoria,ValorCompra
0,8309974263204088,04/26/2024,20:48:37,Vestuário,Loja de Roupas,884.52
1,8309974263204088,04/29/2024,07:40:07,Farmácia,Farmácia,441.16
2,1322170503409537,05/13/2024,13:30:09,Alimentação,Padaria,785.06
3,8309974263204088,04/26/2024,17:41:49,Farmácia,Drogaria,533.74
4,1322170503409537,04/18/2024,06:10:56,Farmácia,Drogaria,867.08
...,...,...,...,...,...,...
95,1322170503409537,05/15/2024,01:33:55,Transporte,Posto de Gasolina,724.72
96,8309974263204088,04/24/2024,19:53:50,Lazer,Parque de Diversões,136.93
97,8309974263204088,05/02/2024,09:40:32,Transporte,Estacionamento,590.57
98,8309974263204088,04/22/2024,09:32:14,Vestuário,Boutique,254.20
99,1322170503409537,04/26/2024,13:07:27,Vestuário,Boutique,458.82

In [ ]:
# .info() exibe informações sobre o DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   NumeroCartao     100 non-null    int64
 1   data_compra      100 non-null    object
 2   hora_compra      100 non-null    object
 3   estabelecimento  100 non-null    object
 4   categoria        100 non-null    object
 5   ValorCompra      100 non-null    float64
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB

Método to_csv()

In [3]:
import pandas as pd

dados = {
    'NomeVendedor': ['Carlos', 'Julia', 'Lucas', 'Fernanda', 'Roberto', 'Camila', 'Ricardo', 'Beatriz', 'Renato', 'Patricia'],
    'QuantidadeVendas': [33, 27, 41, 22, 33, 30, 45, 25, 40, 28],
    'Localidade': ['Sul', 'Nordeste', 'Nordeste', 'Norte', 'Sudeste', 'Sudeste', 'Sudeste', 'Sul', 'Nordeste', 'Centro-Oeste']
}


# Criando novos DataFrames
df = pd.DataFrame(dados)
df

  NomeVendedor  QuantidadeVendas    Localidade
0       Carlos                33           Sul
1        Julia                27      Nordeste
2        Lucas                41      Nordeste
3     Fernanda                22         Norte
4      Roberto                33       Sudeste
5       Camila                30       Sudeste
6      Ricardo                45       Sudeste
7      Beatriz                25           Sul
8       Renato                40      Nordeste
9     Patricia                28  Centro-Oeste

In [ ]:
# to_csv para salvar o DataFrame em um arquivo CSV
df.to_csv("vendas.csv", sep=",", decimal=".")

Método read_excel()

In [ ]:
df =pd.read_excel("excel.xlsx", sheet_name="Python")
df.info()
# pip install xlrd
# Opempyxl é necessário para ler arquivos Excel (.xlsx)

NameError: name 'pd' is not defined

Método read_html()

In [1]:
# pip install lxml para fazer leitura de arquivos HTML
url = "https://www.mat.ufmg.br/futebol/campeao_seriea/"

tabelas = pd.read_html(url)

df = tabelas[0]

df.sort_values(by="Prob(%)", ascending=True)

NameError: name 'pd' is not defined