# Análise de Dados de Vendas com openpyxl

## Introdução

Este notebook realiza uma análise de dados de vendas utilizando a biblioteca `openpyxl` no Python. Vamos ler os dados de um arquivo Excel, realizar diversas manipulações e gerar um relatório final.

In [27]:
### Lendo um arquivo Excel com openpyxl

from openpyxl import load_workbook
import pandas as pd

workbook = load_workbook('vendas.xlsx')         # Carrega o arquivo Excel
sheet = workbook.active                         # Seleciona a planilha ativa
data = []                                       # Lista para armazenar os dados



for linha in sheet.iter_rows(values_only=True): # Percorre as linhas da planilha
    data.append(linha)                          # Adiciona cada linha à lista
    
data[:10]                                       # Exibe as primeiras 10 linhas dos dados

df = pd.DataFrame(data[:10], columns=data[0])   # Cria um DataFrame com os dez primeiros registros
df

,Categoria do Produto,Quantidade,Preço Unitário,Data da Compra,Total Vendas
0,Categoria do Produto,Quantidade,Preço Unitário,Data da Compra,Total Vendas
1,Eletrônicos,12,15.23,2024-11-29,182.76
2,Alimentos,21,19.66,2024-07-11,412.86
3,Alimentos,3,16.28,2024-01-19,48.84
4,Vestuário,21,3.66,2024-12-25,76.86
5,Eletrônicos,21,9.94,2024-05-01,208.74
6,Livros,14,7.6,2024-11-02,106.4
7,Eletrônicos,19,1.45,2024-02-01,27.55
8,Eletrônicos,24,2.92,2024-07-02,70.08
9,Eletrônicos,28,19.93,2024-06-10,558.04

In [28]:
### Calcular o total de vendas para cada produto
totais_vendas ={}      # Dicionário para armazenar os totais de vendas
for row in data[1:]: # Ignora o cabeçalho por não ser necessário
    produto = row[0]  # Primeiro elemento da linha é o produto
    vendas = row[1] * row[2]  # Multiplica quantidade pelo preço unitário
    if produto in totais_vendas:
        totais_vendas[produto] += vendas  # Soma ao total existente
    else:
        totais_vendas[produto] = vendas  # Cria nova entrada no dicionário 
        
print(totais_vendas)  # Exibe o dicionário com os totais de vendas        

totais_vendas_df = pd.DataFrame(totais_vendas.items(), columns=['Produto', 'Total Vendas'])  # Cria DataFrame com totais
totais_vendas_df

{'Eletrônicos': 2517.0800000000004, 'Alimentos': 2112.3199999999997, 'Vestuário': 504.63, 'Livros': 1226.1399999999999}

       Produto  Total Vendas
0  Eletrônicos       2517.08
1    Alimentos       2112.32
2    Vestuário        504.63
3       Livros       1226.14

## Adição de Colunas

In [29]:
sheet['E1'] = 'Total Vendas'  # Adicionando cabeçalho 'totais_vendas' na coluna E1

for i, row in enumerate(sheet.iter_rows(min_row=2, values_only=False), start=2):
    #utiliza a função enumerate junto com sheet.iter_rows para percorrer todas as linhas da planilha
    # a partir da segunda (min_row=2), já que normalmente a primeira linha contém os cabeçalhos
    totais_vendas = row[1].value * row[2].value  # Criando o calculo das posições 1 * 2 a tabela
    sheet[f'E{i}'] = totais_vendas  # atribuindo o valor calculado de totais_vendas à célula correspondente na coluna E da planilha.
    
workbook.save('vendas_atualizado.xlsx')  # Salva o arquivo atualizado

## Adição de Formulas

In [30]:
ultima_linha = len(data)

sheet[f'E{ultima_linha + 1}'] = f'=SUM(E2:E{ultima_linha})'
workbook.save('vendas_Total.xlsx')  # Salva o arquivo atualizado com a fórmula de soma